### PR TITLE
Fix terminal resize logic for Windows

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by ncdc** [comment]
Since we pass stdin/stdout/stderr down from kubectl to each command, I'm wondering if it might be nicer to:
1. Modify https://github.com/kubernetes/kubernetes/blob/61a9358dbd214aec9f500a2bf791e3e088dd484a/cmd/kubectl/app/kubectl.go#L31 to use term.StdStreams() (and the same for cmd/hyperkube/kubectl.go)
2. Modify https://github.com/kubernetes/kubernetes/blob/61a9358dbd214aec9f500a2bf791e3e088dd484a/pkg/util/term/term.go#L32-L44 to have In and Out (and Err?)

**Comment by sttts** [comment]
I would guess for testing we pass in other reader/writers.

**Comment by ncdc** [comment]
You could also theoretically do `cat somefile.txt | kubectl attach -it mypod` to attach (or exec) and have somefile.txt drive a program that does need to display to a TTY, including handling resize events.

**Comment by sttts** [comment]
I have simplified the patch by putting In and Out into the TTY. Tested on Windows 7 and Linux.

Your `cat somefile.txt | kubectl attach -it mypod` is a good one. I guess `p.In` would not be a terminal, but `p.Out` would. The current implementation will disable the terminal mode then. Probably, that behavior is ok though. I cannot think of any real use-case where you pipe something into an interactive command.

**Comment by sttts** [comment]
I see you have done basically the same changes. Then this PR can be closed.

**Pull request closed without merging**
